### ISSUE TITLE
저장했던 게임을 continue 했을 시 점수가 저장이 되지 않는 현상 발견.

### ISSUE THREAD

**Issue by Leeinsu1** [18-2-SKKU-OSS/2018-2-OSS-E6#1]
코드 상의 에러로 생각이 됩니다.
--윤재한

**Comment by yjh1534** [comment]
게임을 저장할 경우 txt 파일로 출력하여 저장해두는데, 저장한 파일의 수정이 쉬워 저장해둔 게임의 점수를 scoreboard에 올릴 경우 쉽게 고득점을 할 수 있습니다. 이런 행위를 방지하기 위하여 저장했던 게임을 continue하면 점수를 저장할 수 없도록 하였습니다. 이를 해결하려면 저장한 데이터를 서버와 같이 다른 곳에 보관하거나 파일을 열어볼 수 없도록 하는 방법이 있습니다.

첫번째 방법의 경우는 현실적으로 불가능한 방법이라고 판단하였고, 두번째 방법의 경우, 파일을 저장할 때 읽기전용으로 저장한다고 하여도 Linux에서 직접 파일 권한을 수정할 수 있기에 의미가 없다고 판단하였습니다.
