### ISSUE TITLE
게임이 끝난 후 바로 프로그램이 종료가 된다.

### ISSUE THREAD

**Issue by Leeinsu1** [18-2-SKKU-OSS/2018-2-OSS-E6#2]
retry 버튼과 exit 버튼을 만들어서 게임 한판 종료 후 다시 게임을 할지 결정 할 수 있게 하려 한다.

**Comment by yhjsoar** [comment]
game play 끝난 후, 

1.Play a new game
2. Go back to menu 
3. Exit

3가지 선택지에서 선택하게 한 후 선택에 따라 실행되게 변경했습니다.

**Comment by yhjsoar** [comment]
1~3 이외의 선택지를 고를 경우의 문제 상황 발생

**Comment by yhjsoar** [comment]
해결 완료
